import { Icon } from "@iconify-icon/react"
import { type NextPage } from "next"
import Head from "next/head"

import {
	BottomNavigation,
	BottomNavigationAction,
	Box,
	Button,
	Paper,
	Typography
} from "@mui/material"

import React from "react"

const HealthHub: NextPage = () => {
	const [value, setValue] = React.useState(0)

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box sx={{ pb: 7 }}>
				<Typography variant="h5">
					Daily check-in
				</Typography>
				<Typography variant="body1">
					Have you checked in today? Keep your streak going!
				</Typography>
				<Button variant="contained" sx={{ my: "8px" }}>
					Complete check-in
				</Button>
				<Paper
					sx={{ position: "fixed", bottom: 0, left: 0, right: 0 }}
					elevation={3}
				>
					<BottomNavigation
						showLabels
						value={value}
						onChange={(event, newValue: number) => {
							setValue(newValue)
						}}
					>
						<BottomNavigationAction
							label="Home"
							icon={<Icon icon="material-symbols:home" height={24} />}
						/>
						<BottomNavigationAction
							label="History"
							icon={<Icon icon="material-symbols:history" height={24} />}
						/>
						<BottomNavigationAction
							label="Archive"
							icon={<Icon icon="material-symbols:settings" height={24} />}
						/>
					</BottomNavigation>
				</Paper>
			</Box>
		</>
	)
}

export default HealthHub
