import { Icon } from "@iconify-icon/react"
import { type NextPage } from "next"
import Head from "next/head"

import {
	BottomNavigation,
	BottomNavigationAction,
	Box,
	Button,
	Card,
	CardContent,
	Divider,
	Paper,
	Stack,
	Typography,
} from "@mui/material"
import { useTheme } from "@mui/material/styles"
import React from "react"

const HealthHub: NextPage = () => {
	const theme = useTheme()
	const [value, setValue] = React.useState(0)

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box sx={{ p: theme.spacing(2) }}>
				<Typography variant="h4" gutterBottom>
					Good morning
				</Typography>
				<Typography
					variant="caption"
					sx={{
						display: "flex",
						justifyContent: "end",
						color: theme.palette.text.secondary,
					}}
				>
					Last Updated: 15/5/2023
				</Typography>

				<Card sx={{ minWidth: 275, my: theme.spacing(2) }}>
					<CardContent
						component={Stack}
						direction="row"
						justifyContent="space-around"
						divider={<Divider orientation="vertical" flexItem />}
						sx={{ px: theme.spacing(1), py: theme.spacing(3) }}
					>
						<Box
							sx={{
								display: "flex",
								flexDirection: "column",
								justifyContent: "center",
								alignItems: "center",
							}}
						>
							<Typography variant="h5">0 day</Typography>
							<Typography variant="subtitle1" color="text.secondary">
								Current Streak
							</Typography>
						</Box>
						<Box
							sx={{
								display: "flex",
								flexDirection: "column",
								justifyContent: "center",
								alignItems: "center",
							}}
						>
							<Typography variant="h5">5 day</Typography>
							<Typography variant="subtitle1" color="text.secondary">
								Longest Streak
							</Typography>
						</Box>
					</CardContent>
				</Card>

				<Box
					sx={{
						display: "flex",
						justifyContent: "space-between",
						alignItems: "center",
						flexWrap: "wrap",
						gap: theme.spacing(2),
						mb: theme.spacing(1),
					}}
				>
					<Card sx={{ minWidth: 100 }}>
						<CardContent
							sx={{
								p: theme.spacing(2) + "!important",
								display: "flex",
								flexDirection: "column",
								justifyContent: "center",
								alignItems: "center",
							}}
						>
							<Icon
								icon="mdi:heart-pulse"
								height={24}
								style={{ color: theme.palette.secondary.main }}
							/>
							<Typography variant="h5">85</Typography>
							<Typography variant="subtitle1" color="text.secondary">
								bpm
							</Typography>
						</CardContent>
					</Card>
					<Card sx={{ minWidth: 100 }}>
						<CardContent
							sx={{
								p: theme.spacing(2) + "!important",
								display: "flex",
								flexDirection: "column",
								justifyContent: "center",
								alignItems: "center",
							}}
						>
							<Icon
								icon="mdi:sleep-schedule"
								height={24}
								style={{ color: theme.palette.secondary.main }}
							/>
							<Typography variant="h5">7h 30m</Typography>
							<Typography variant="subtitle1" color="text.secondary">
								sleep
							</Typography>
						</CardContent>
					</Card>
					<Card sx={{ minWidth: 100 }}>
						<CardContent
							sx={{
								p: theme.spacing(2) + "!important",
								display: "flex",
								flexDirection: "column",
								justifyContent: "center",
								alignItems: "center",
							}}
						>
							<Icon
								icon="mdi:walk"
								height={24}
								style={{ color: theme.palette.secondary.main }}
							/>
							<Typography variant="h5">1281</Typography>
							<Typography variant="subtitle1" color="text.secondary">
								steps
							</Typography>
						</CardContent>
					</Card>
				</Box>

				<Typography variant="h5" sx={{ mt: theme.spacing(2) }}>
					Daily check-in
				</Typography>
				<Typography variant="body1" gutterBottom sx={{ mb: theme.spacing(1) }}>
					Have you checked in today? Keep your streak going!
				</Typography>
				<Button variant="contained">Complete check-in</Button>

				<Typography variant="h5" sx={{ mt: theme.spacing(2) }}>
					Medication
				</Typography>
				<Box
					sx={{
						display: "flex",
						justifyContent: "space-between",
						px: "1px",
						py: theme.spacing(2),
						gap: theme.spacing(2),
						mb: theme.spacing(1),
						overflow: "auto",
					}}
				>
					<Card sx={{ minWidth: theme.spacing(17) }}>
						<CardContent
							sx={{
								px: theme.spacing(2),
								py: theme.spacing(1) + "!important",
								display: "flex",
								flexDirection: "column",
							}}
						>
							<Icon
								icon="mdi:pill"
								height={24}
								style={{ color: theme.palette.secondary.main }}
							/>
							<Typography variant="subtitle1">Enezab</Typography>
							<Typography variant="body1" color="text.secondary">
								Take 1 between meals
							</Typography>
						</CardContent>
					</Card>
					<Card sx={{ minWidth: theme.spacing(17) }}>
						<CardContent
							sx={{
								px: theme.spacing(2),
								py: theme.spacing(1) + "!important",
								display: "flex",
								flexDirection: "column",
							}}
						>
							<Icon
								icon="mdi:pill"
								height={24}
								style={{ color: theme.palette.secondary.main }}
							/>
							<Typography variant="subtitle1">Zermir</Typography>
							<Typography variant="body1" color="text.secondary">
								Take 3 after lunch
							</Typography>
						</CardContent>
					</Card>
					<Card sx={{ minWidth: theme.spacing(17) }}>
						<CardContent
							sx={{
								px: theme.spacing(2),
								py: theme.spacing(1) + "!important",
								display: "flex",
								flexDirection: "column",
							}}
						>
							<Icon
								icon="mdi:pill"
								height={24}
								style={{ color: theme.palette.secondary.main }}
							/>
							<Typography variant="subtitle1">Enezab</Typography>
							<Typography variant="body1" color="text.secondary">
								Take 1 between meals
							</Typography>
						</CardContent>
					</Card>
				</Box>

				<Paper
					sx={{ position: "fixed", bottom: 0, left: 0, right: 0 }}
					elevation={3}
				>
					<BottomNavigation
						showLabels
						value={value}
						onChange={(event, newValue: number) => {
							setValue(newValue)
						}}
					>
						<BottomNavigationAction
							label="Home"
							icon={<Icon icon="material-symbols:home" height={24} />}
						/>
						<BottomNavigationAction
							label="History"
							icon={<Icon icon="material-symbols:history" height={24} />}
						/>
						<BottomNavigationAction
							label="Archive"
							icon={<Icon icon="material-symbols:settings" height={24} />}
						/>
					</BottomNavigation>
				</Paper>
			</Box>
		</>
	)
}

export default HealthHub
