import { type NextPage } from "next"
import { signIn, signOut, useSession } from "next-auth/react"
import Head from "next/head"

import Link from "@components/atoms/Link"
import {
	Box,
	Button,
	Card,
	CardActionArea,
	CardContent,
	Typography,
} from "@mui/material"
import { api } from "@utils/api"

const Home: NextPage = () => {
	const { data: sessionData } = useSession()

	const { data: secretMessage } = api.example.getSecretMessage.useQuery(
		undefined, // no input
		{ enabled: sessionData?.user !== undefined }
	)

	const hello = api.example.hello.useQuery({ text: "from tRPC" })

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box
				component="main"
				sx={{
					px: 4,
					pt: 4,
					pb: 8,
					border: "1px dashed grey",
					m: 4,
					display: "flex",
					flexDirection: "column",
					justifyContent: "center",
					alignItems: "center",
				}}
			>
				<h1>T3 + MUI Example</h1>
				<Box
					sx={{
						display: "flex",
						alignItems: "center",
						flexDirection: "column",
						justifyContent: "center",
					}}
				>
					<p>{hello.data ? hello.data.greeting : "Loading tRPC query..."}</p>
					{sessionData && secretMessage && (
						<>
							<p>Logged in as {sessionData.user?.name}.</p>
							<code>{secretMessage}</code>
						</>
					)}

					<Button
						sx={{ margin: "10px" }}
						variant="contained"
						onClick={sessionData ? () => void signOut() : () => void signIn()}
					>
						{sessionData ? "Sign out" : "Sign in"}
					</Button>
				</Box>

				<Box
					sx={{
						display: "flex",
						flexDirection: "row",
						gap: "20px",
						mt: "10px",
					}}
				>
					<Card sx={{ maxWidth: 345 }}>
						<Link href="/kitchensink" sx={{ textDecoration: "inherit" }}>
							<CardActionArea sx={{ height: "100%" }}>
								<CardContent>
									<Typography gutterBottom variant="h5" component="div">
										Kitchen Sink
									</Typography>
									<Typography variant="body2" color="text.secondary">
										A playground of themed MUI components
									</Typography>
								</CardContent>
							</CardActionArea>
						</Link>
					</Card>

					<Card sx={{ maxWidth: 345 }}>
						<Link href="/healthhub" sx={{ textDecoration: "none" }}>
							<CardActionArea>
								<CardContent>
									<Typography gutterBottom variant="h5" component="div">
										health hub
									</Typography>
									<Typography variant="body2" color="text.secondary">
										A mock application empowering individuals to take control of
										their health and wellness and make it easy to manage their
										health information.
									</Typography>
								</CardContent>
							</CardActionArea>
						</Link>
					</Card>
				</Box>
			</Box>
		</>
	)
}

export default Home
